spring.application.name=curso-dev-full

# Mostrar mais detalhes
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.orm=DEBUG

# DATASOURCE
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=gregoriohd
spring.datasource.password=123g456g

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Para criar as tabelas do zero
spring.jpa.hibernate.ddl-auto=update
